### PR TITLE
Fix makefile

### PR DESCRIPTION
**Pull request by jwhite3**
#6 fix

### CODE REVIEW

**Comment by jwhite3** [comment]
@aliciacanipe Take a look and see if this works for you as well

**Comment by aliciacanipe** [comment]
Hm. `make riadocs` completes without error:

make_riadocs

But I still get an error when trying to run `make gh-pages`:

make_ghpages

Could it be an issue with the `version_control` module or is it just erroring out after that line for some other reason?

**Comment by aliciacanipe** [comment]
Also, I don't really know much about Sphinx and the code in Makefile -- is there any way to get more informative errors to make troubleshooting easier for future training doc GitHub-ers?

**Comment by jwhite3** [comment]
Hmmm... I didn't have that issue when I ran it. Something in your local repo must be different

There probably is, but that would require doing some extensive updating to our auto-building tools. I wouldn't be able to work on that at this point.

**Comment by jwhite3** [comment]
You might try pulling to make sure that your repo is up to date, but if it is and you're still getting that error, I'd try to do it on a "clean" repo (delete your current one then clone again. Assuming you don't have a ton of unsaved work)

**Comment by aliciacanipe** [comment]
Yeah, that's what I did earlier today -- I completely deleted the old repo, started a new directory for testing, and cloned the latest version (from this afternoon-ish). Then I ran `make riadocs` and `make gh-pages`, so I'm not sure how mine could be different from yours. I'll keep trying to sort it out, though. Thanks!

**Pull request merged**
