### PR TITLE
remove support for Python2.7; readability refactor; PEP8 compliance

### PR DESCRIPTION
**Pull request by jwhite3**
Biggest thing about this update is the removal of python 2.7 support. (only works with python 3.5+)

This refactor is mostly cosmetic  otherwise. 

@julesfowler @tddesjardins I've requested reviews from you two since you've been the most active on the docs recently. Let me know what you guys think

### CODE REVIEW

**Comment by tddesjardins** [comment]
The ever important question: did you test it? :P

**Comment by jwhite3** [comment]
@tddesjardins Yep! I also might've figured out why you weren't seeing changes sometimes. Occasionally you have to refresh the page a couple of times so that the watcher picks up the file changes. Not sure why that happens though

**Comment by tddesjardins** [comment]
Okay, I just tested it myself and it seems to work, but I am getting  this exception occasionally while autobuilder is running:
```
Exception happened during processing of request from ('127.0.0.1', 50597)
Traceback (most recent call last):
  File "/Users/desjard/miniconda3/envs/astroconda/lib/python3.5/socketserver.py", line 313, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/Users/desjard/miniconda3/envs/astroconda/lib/python3.5/socketserver.py", line 341, in process_request
    self.finish_request(request, client_address)
  File "/Users/desjard/miniconda3/envs/astroconda/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/Users/desjard/miniconda3/envs/astroconda/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/Users/desjard/miniconda3/envs/astroconda/lib/python3.5/http/server.py", line 422, in handle
    self.handle_one_request()
  File "/Users/desjard/miniconda3/envs/astroconda/lib/python3.5/http/server.py", line 410, in handle_one_request
    method()
  File "/Users/desjard/miniconda3/envs/astroconda/lib/python3.5/http/server.py", line 648, in do_GET
    self.copyfile(f, self.wfile)
  File "/Users/desjard/miniconda3/envs/astroconda/lib/python3.5/http/server.py", line 809, in copyfile
    shutil.copyfileobj(source, outputfile)
  File "/Users/desjard/miniconda3/envs/astroconda/lib/python3.5/shutil.py", line 82, in copyfileobj
    fdst.write(buf)
  File "/Users/desjard/miniconda3/envs/astroconda/lib/python3.5/socket.py", line 594, in write
    return self._sock.send(b)
BrokenPipeError: [Errno 32] Broken pipe
```

**Comment by jwhite3** [comment]
@tddesjardins weird. No idea why the pipe to the server would break. Try running it in python 3.6
They made some updates to the `https.server` module that might prevent that issue. Is it preventing you from using the auto builder?

**Comment by tddesjardins** [comment]
Weird, I'm still getting the broken pipe error. However, it does seem to still function correctly. I tried editing a file several times and reloading the page. It does notice that the file was updated each time and correctly displays it. Given that it's functioning, I'm content to approve the PR if @julesfowler agrees.

**Pull request merged**
